
const constants = {
    GET_REQUEST: "@movie/GET_REQUEST",
    GET_SUCCESS: "@movie/GET_SUCCESS",
    GET_FAILURE: "@movie/GET_FAILURE",

    CREATE_REQUEST: "@movie/CREATE_REQUEST",
    CREATE_SUCCESS: "@movie/CREATE_SUCCESS",
    CREATE_FAILURE: "@movie/CREATE_FAILURE",

    GET_INFO_REQUEST: "@movie/GET_INFO_REQUEST",
    GET_INFO_SUCCESS: "@movie/GET_INFO_SUCCESS",
    GET_INFO_FAILURE: "@movie/GET_INFO_FAILURE",

    UPDATE_REQUEST: "@movie/UPDATE_REQUEST",
    UPDATE_SUCCESS: "@movie/UPDATE_SUCCESS",
    UPDATE_FAILURE: "@movie/UPDATE_FAILURE",

    DELETE_REQUEST: "@movie/DELETE_REQUEST",
    DELETE_SUCCESS: "@movie/DELETE_SUCCESS",
    DELETE_FAILURE: "@movie/DELETE_FAILURE",
}

export { constants };