
const constants = {
    GET_REQUEST: "@cast/GET_MOVIE",
    GET_SUCCESS: "@cast/GET_SUCCESS",
    GET_FAILURE: "@cast/GET_FAILURE",

    CREATE_REQUEST: "@cast/CREATE_REQUEST",
    CREATE_SUCCESS: "@cast/CREATE_SUCCESS",
    CREATE_FAILURE: "@cast/CREATE_FAILURE",

    GET_INFO_REQUEST: "@cast/GET_INFO_REQUEST",
    GET_INFO_SUCCESS: "@cast/GET_INFO_SUCCESS",
    GET_INFO_FAILURE: "@cast/GET_INFO_FAILURE",

    UPDATE_REQUEST: "@cast/UPDATE_REQUEST",
    UPDATE_SUCCESS: "@cast/UPDATE_SUCCESS",
    UPDATE_FAILURE: "@cast/UPDATE_FAILURE",

    DELETE_REQUEST: "@cast/DELETE_REQUEST",
    DELETE_SUCCESS: "@cast/DELETE_SUCCESS",
    DELETE_FAILURE: "@cast/DELETE_FAILURE",
}

export { constants };