
const constants = {
    GET_REQUEST: "@genre/GET_REQUEST",
    GET_SUCCESS: "@genre/GET_SUCCESS",
    GET_FAILURE: "@genre/GET_FAILURE",

    CREATE_REQUEST: "@genre/CREATE_REQUEST",
    CREATE_SUCCESS: "@genre/CREATE_SUCCESS",
    CREATE_FAILURE: "@genre/CREATE_FAILURE",

    GET_INFO_REQUEST: "@genre/GET_INFO_REQUEST",
    GET_INFO_SUCCESS: "@genre/GET_INFO_SUCCESS",
    GET_INFO_FAILURE: "@genre/GET_INFO_FAILURE",

    UPDATE_REQUEST: "@genre/UPDATE_REQUEST",
    UPDATE_SUCCESS: "@genre/UPDATE_SUCCESS",
    UPDATE_FAILURE: "@genre/UPDATE_FAILURE",

    DELETE_REQUEST: "@genre/DELETE_REQUEST",
    DELETE_SUCCESS: "@genre/DELETE_SUCCESS",
    DELETE_FAILURE: "@genre/DELETE_FAILURE",
}

export { constants };